name: weather_track
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  http: ^1.2.2
  easy_search_bar: ^2.5.0
  google_sign_in: ^6.2.1
  intl: ^0.17.0
  connectivity_plus: ^6.0.5
  internet_connection_checker_plus: ^2.5.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/star 8.png
    - assets/star 8@2x.png
    - assets/star 8@3x.png
    - assets/img.png
